name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Create .env.test file
        run: echo "DATABASE_URL=postgres://postgres:password@localhost:5433" >> .env.test

      - name: Install dependencies
        run: npm install

      - name: ESlint
        run: npm run eslint:check

      - name: Prettier
        run: npm run prettier:check

      - name: Test
        run: npm run test

  migrate:
    runs-on: ubuntu-latest

    needs: check

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Make envfile
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.test

      - name: Run migrations
        run: npx prisma migrate deploy
